#!/usr/bin/env bats

load test_helper

setup() {
  setup_test_env
  export TEST_PROJECT="$(mktemp -d)"
  export CALL_LOG="$TEST_PROJECT/calls.log"

  export FAKE_CODEX="$TEST_PROJECT/real-codex"
  cat > "$FAKE_CODEX" <<'EOF'
#!/usr/bin/env bash
printf 'real-codex' >> "$CALL_LOG"
for arg in "$@"; do
  printf ' <%s>' "$arg" >> "$CALL_LOG"
done
printf '\n' >> "$CALL_LOG"
EOF
  chmod +x "$FAKE_CODEX"

  export FAKE_MONITOR="$TEST_PROJECT/monitor"
  cat > "$FAKE_MONITOR" <<'EOF'
#!/usr/bin/env bash
printf 'monitor real=%s' "${AGMSG_REAL_CODEX:-}" >> "$CALL_LOG"
for arg in "$@"; do
  printf ' <%s>' "$arg" >> "$CALL_LOG"
done
printf '\n' >> "$CALL_LOG"
EOF
  chmod +x "$FAKE_MONITOR"
}

teardown() {
  rm -rf "$TEST_PROJECT"
  teardown_test_env
}

@test "codex shim: monitor project routes resume through codex-monitor" {
  bash "$SCRIPTS/delivery.sh" set monitor codex "$TEST_PROJECT" >/dev/null

  run bash -c 'cd "$TEST_PROJECT" && AGMSG_REAL_CODEX="$FAKE_CODEX" AGMSG_CODEX_MONITOR_CMD="$FAKE_MONITOR" bash "$SCRIPTS/codex-shim.sh" resume --last'

  [ "$status" -eq 0 ]
  grep -q "monitor real=$FAKE_CODEX <--project> <$TEST_PROJECT> <--codex-command> <resume> <--> <--last>" "$CALL_LOG"
}

@test "codex shim: monitor project routes prompt launches through top-level codex" {
  bash "$SCRIPTS/delivery.sh" set monitor codex "$TEST_PROJECT" >/dev/null

  run bash -c 'cd "$TEST_PROJECT" && AGMSG_REAL_CODEX="$FAKE_CODEX" AGMSG_CODEX_MONITOR_CMD="$FAKE_MONITOR" bash "$SCRIPTS/codex-shim.sh" "fix this"'

  [ "$status" -eq 0 ]
  grep -q "monitor real=$FAKE_CODEX <--project> <$TEST_PROJECT> <--codex-command> <codex> <--> <fix this>" "$CALL_LOG"
}

@test "codex shim: 'both' delivery mode also routes through codex-monitor" {
  # `set both codex` is rejected by the codex bridge beta, but a project can end
  # up in `both` via the claude-code flow / older installs. `both` = monitor
  # primary, so the bridge must still engage (exact-`monitor`-only used to let
  # `both` projects pass through to bare codex with no bridge). Stub delivery.sh's
  # status to report it.
  cat > "$SCRIPTS/delivery.sh" <<'EOF'
#!/usr/bin/env bash
[ "$1" = "status" ] && { echo "mode: both"; exit 0; }
exit 0
EOF
  chmod +x "$SCRIPTS/delivery.sh"

  run bash -c 'cd "$TEST_PROJECT" && AGMSG_REAL_CODEX="$FAKE_CODEX" AGMSG_CODEX_MONITOR_CMD="$FAKE_MONITOR" bash "$SCRIPTS/codex-shim.sh" resume --last'

  [ "$status" -eq 0 ]
  grep -q "monitor real=$FAKE_CODEX <--project> <$TEST_PROJECT> <--codex-command> <resume> <--> <--last>" "$CALL_LOG"
}

@test "codex shim: non-monitor project passes through to real codex" {
  bash "$SCRIPTS/delivery.sh" set turn codex "$TEST_PROJECT" >/dev/null

  AGMSG_REAL_CODEX="$FAKE_CODEX" AGMSG_CODEX_MONITOR_CMD="$FAKE_MONITOR" \
    run bash "$SCRIPTS/codex-shim.sh" resume --last

  [ "$status" -eq 0 ]
  grep -q "real-codex <resume> <--last>" "$CALL_LOG"
  ! grep -q "^monitor" "$CALL_LOG"
}

@test "codex shim: noninteractive codex subcommands pass through even in monitor mode" {
  bash "$SCRIPTS/delivery.sh" set monitor codex "$TEST_PROJECT" >/dev/null

  AGMSG_REAL_CODEX="$FAKE_CODEX" AGMSG_CODEX_MONITOR_CMD="$FAKE_MONITOR" \
    run bash "$SCRIPTS/codex-shim.sh" exec echo hi

  [ "$status" -eq 0 ]
  grep -q "real-codex <exec> <echo> <hi>" "$CALL_LOG"
  ! grep -q "^monitor" "$CALL_LOG"
}

@test "codex shim: --cd project is used for monitor detection" {
  bash "$SCRIPTS/delivery.sh" set monitor codex "$TEST_PROJECT" >/dev/null

  AGMSG_REAL_CODEX="$FAKE_CODEX" AGMSG_CODEX_MONITOR_CMD="$FAKE_MONITOR" \
    run bash "$SCRIPTS/codex-shim.sh" --cd "$TEST_PROJECT" resume

  [ "$status" -eq 0 ]
  grep -q "monitor real=$FAKE_CODEX <--project> <$TEST_PROJECT> <--codex-command> <resume> <--> <--cd> <$TEST_PROJECT>" "$CALL_LOG"
}

@test "codex shim install: installed bin wrapper still finds skill scripts" {
  export HOME="$TEST_PROJECT/home"
  mkdir -p "$HOME"
  bash "$SCRIPTS/delivery.sh" set monitor codex "$TEST_PROJECT" >/dev/null
  [ -x "$HOME/.agents/bin/codex" ]

  PATH="$HOME/.agents/bin:$PATH" run bash -c 'cd "$TEST_PROJECT" && AGMSG_REAL_CODEX="$FAKE_CODEX" AGMSG_CODEX_MONITOR_CMD="$FAKE_MONITOR" codex resume'

  [ "$status" -eq 0 ]
  grep -q "monitor real=$FAKE_CODEX <--project> <$TEST_PROJECT> <--codex-command> <resume> <-->" "$CALL_LOG"
}

@test "codex shim install: drops a Windows codex.cmd wrapper under Git Bash" {
  # The extensionless bash shim is unrunnable from PowerShell/cmd; on Windows the
  # installer also writes a codex.cmd that re-enters Git Bash into the same shim.
  case "$(uname -s 2>/dev/null || echo unknown)" in
    MINGW*|MSYS*|CYGWIN*) ;;
    *) skip "codex.cmd is only generated on native Windows (Git Bash)" ;;
  esac
  export HOME="$TEST_PROJECT/home"
  mkdir -p "$HOME"
  bash "$SCRIPTS/delivery.sh" set monitor codex "$TEST_PROJECT" >/dev/null

  [ -f "$HOME/.agents/bin/codex.cmd" ]
  grep -q "generated by agmsg" "$HOME/.agents/bin/codex.cmd"
  # Routes back through Git Bash into the extensionless bash shim.
  grep -q 'AGMSG_CMD_BASH' "$HOME/.agents/bin/codex.cmd"
  grep -qF "$HOME/.agents/bin/codex" "$HOME/.agents/bin/codex.cmd"
  # Disarms a user .bash_profile winpty self-wrap that would otherwise hijack the
  # login shell into an interactive prompt instead of running the shim.
  grep -q 'WINPTY_SPAWNED' "$HOME/.agents/bin/codex.cmd"

  # `remove` takes the wrapper with it (only the agmsg-generated one).
  bash "$SCRIPTS/codex-shim-install.sh" remove >/dev/null 2>&1
  [ ! -f "$HOME/.agents/bin/codex.cmd" ]
  [ ! -f "$HOME/.agents/bin/codex" ]
}
