#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
AGENTS_BIN="$HOME/.agents/bin"
TARGET="$AGENTS_BIN/codex"

usage() {
  cat <<EOF
Usage: codex-shim-install.sh [install|remove|status]

Installs an optional agmsg Codex shim at:
  $TARGET

Put ~/.agents/bin before the real Codex binary on PATH. The shim only routes
interactive Codex launches through agmsg's monitor bridge when the current
project is in Codex monitor mode.
EOF
}

is_agmsg_shim() {
  [ -f "$TARGET" ] && grep -q "Optional Codex entrypoint shim for agmsg monitor mode" "$TARGET" 2>/dev/null
}

shell_quote() {
  printf '%q' "$1"
}

cmd="${1:-install}"
case "$cmd" in
  -h|--help)
    usage
    ;;
  install)
    mkdir -p "$AGENTS_BIN"
    if [ -e "$TARGET" ] && ! is_agmsg_shim; then
      echo "codex-shim-install: refusing to overwrite existing $TARGET" >&2
      echo "codex-shim-install: move it aside or remove it first" >&2
      exit 1
    fi
    {
      echo "#!/usr/bin/env bash"
      echo "set -euo pipefail"
      echo ""
      echo "# Optional Codex entrypoint shim for agmsg monitor mode."
      echo "# Generated by agmsg. Dispatches to the installed skill script."
      echo ""
      echo "export AGMSG_CODEX_SHIM_WRAPPER=1"
      echo "export AGMSG_CODEX_SHIM_SCRIPT_DIR=$(shell_quote "$SCRIPT_DIR")"
      echo "export AGMSG_CODEX_SHIM_TARGET=$(shell_quote "$TARGET")"
      echo "exec $(shell_quote "$SCRIPT_DIR/codex-shim.sh") \"\$@\""
    } > "$TARGET"
    chmod +x "$TARGET"
    # Windows: also drop a codex.cmd. PowerShell/cmd cannot run the extensionless
    # bash shim — they resolve a bare `codex` to it ahead of the real codex.exe
    # and then error "Cannot run a document in the middle of a pipeline", so
    # without this `codex` is broken outside Git Bash. PATHEXT makes PowerShell/cmd
    # prefer the .cmd, which routes back through Git Bash into the same shim; Git
    # Bash keeps using the extensionless `codex`. Backslash paths go through printf
    # %s args so escape interpretation does not mangle them.
    case "$(uname -s 2>/dev/null || echo unknown)" in
      MINGW*|MSYS*|CYGWIN*)
        cmd_target="$AGENTS_BIN/codex.cmd"
        default_bash='C:\Program Files\Git\bin\bash.exe'
        {
          printf '@echo off\r\n'
          printf 'rem agmsg Codex monitor shim (Windows) -- generated by agmsg.\r\n'
          printf 'rem Routes `codex` through Git Bash into the bash entrypoint shim.\r\n'
          printf 'rem A user .bash_profile may self-wrap a login TTY into an interactive\r\n'
          printf 'rem shell (exec winpty bash -i); that would hijack `bash -l <shim>`\r\n'
          printf 'rem before it runs the shim. Mark the winpty wrap as already done so\r\n'
          printf 'rem the profile skips it -- launched from a Windows console, codex.exe\r\n'
          printf 'rem still gets a real terminal.\r\n'
          printf 'set "WINPTY_SPAWNED=1"\r\n'
          printf 'set "AGMSG_CMD_BASH=%%GIT_BASH%%"\r\n'
          printf 'if "%%AGMSG_CMD_BASH%%"=="" set "AGMSG_CMD_BASH=%%AGMSG_BASH%%"\r\n'
          printf 'if "%%AGMSG_CMD_BASH%%"=="" set "AGMSG_CMD_BASH=%s"\r\n' "$default_bash"
          printf '"%%AGMSG_CMD_BASH%%" -l "%s" %%*\r\n' "$TARGET"
        } > "$cmd_target"
        ;;
    esac
    if [ "${AGMSG_CODEX_SHIM_INSTALL_QUIET:-}" != "1" ]; then
      echo "installed: $TARGET"
      case ":$PATH:" in
        *":$AGENTS_BIN:"*) ;;
        *)
          echo "note: add $AGENTS_BIN before the real Codex binary on PATH"
          ;;
      esac
    fi
    ;;
  remove|uninstall)
    if is_agmsg_shim; then
      rm -f "$TARGET"
      # Drop the Windows wrapper too, but only if it is the agmsg-generated one.
      if [ -f "$AGENTS_BIN/codex.cmd" ] && grep -q "generated by agmsg" "$AGENTS_BIN/codex.cmd" 2>/dev/null; then
        rm -f "$AGENTS_BIN/codex.cmd"
      fi
      echo "removed: $TARGET"
    elif [ -e "$TARGET" ]; then
      echo "codex-shim-install: $TARGET exists but is not the agmsg shim; leaving it untouched" >&2
      exit 1
    else
      echo "not installed: $TARGET"
    fi
    ;;
  status)
    if is_agmsg_shim; then
      echo "installed: $TARGET"
    else
      echo "not installed: $TARGET"
    fi
    ;;
  *)
    usage >&2
    exit 1
    ;;
esac
